### ISSUE TITLE
Invalid cert for 1.1.1.1

### ISSUE THREAD

**Issue by GGGunrunner** [leighmcculloch/dnsovertlsproxy#1]
Thanks for writing this great tool! Two questions:

1. I'm trying to run it on Win7 in Vbox (for testing), had set DNS as 127.0.0.1 in system-wide settings, but I'm getting this:

> dnsovertlsproxy -listen :53 -server 1.1.1.1:853
2018/06/25 05:29:26 error x509: certificate is valid for 1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001, not 1.1.1.1

and

2. I also would like to deploy it on several old computers running Win 2003 Server. The Root CA bundle seems to be up-to-date, but I'm getting:

> dnsovertlsproxy -listen :53 -server 1.1.1.1:853
2018/06/25 05:36:34 error x509: certificate signed by unknown authority

Seems that the cert at 1.1.1.1 is issued/signed by CA that is still not in my chain. Any fix for that?

Many thanks!

**Comment by leighmcculloch** [comment]
These two issues seem unrelated, although similar.

1. The error about the certificate being valid for multiple IPs and not just one seems like the verifier isn't distinguishing that the certificate is valid for one of the IPs, maybe this is a bug with the Go TLS library? I'll look more into this and report back.

2. This is very likely to do with the Win 2003 server not having the root CA that's in use. You could try and install updated root CAs from Microsoft, but I don't know if they support it. You might like to start here, but no guarantees. https://technet.microsoft.com/en-us/library/bb735413.aspx?f=255&MSPPError=-2147217396

**Comment by leighmcculloch** [comment]
Closing the issue due to inactivity. Please reopen if needed.
