### ISSUE TITLE
How to resolve ipv6 address?

### ISSUE THREAD

**Issue by linsui** [leighmcculloch/dnsovertlsproxy#2]
When I try to resolve an ipv6 host it return nothing.

**Comment by leighmcculloch** [comment]
Hey @linsui, thanks for opening the issue. Did you find out what the problem was?

**Comment by linsui** [comment]
I'm sorry. It's my fault. When I add AAAA behind dig I get the right IP.

**Comment by leighmcculloch** [comment]
No worries! I've definitely made that mistake too! Easy fix!
